DROP TABLE CATEGORIES CASCADE CONSTRAINTS;

DROP SEQUENCE S_CATEGORIES;

CREATE SEQUENCE S_CATEGORIES
  START WITH 1
  MAXVALUE 1E27
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE CATEGORIES  (
   CATEGORY_ID          NUMBER(6)                        NOT NULL,
   CATEGORY_NAME        VARCHAR2(32),
   CATEGORY_GUID        VARCHAR2(36)
)
NOLOGGING 
NOCACHE 
NOPARALLEL;