DROP TABLE SIMPLES CASCADE CONSTRAINTS;

CREATE TABLE SIMPLES (
   ID INTEGER NOT NULL,
   NAME VARCHAR(64) NULL ,
   ADDRESS VARCHAR(64) NULL ,
   COUNT INTEGER NULL ,
   "DATE" DATE NULL,
   PAY DECIMAL(18,2) NULL,
   CONSTRAINT PK_SIMPLES PRIMARY KEY (ID)
)
NOLOGGING 
NOCACHE 
NOPARALLEL;